# -*- coding: utf-8 -*-
"""assignment__(1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k7yPz3_pIQPfaHaqxwOEyCiyRreGgurM

1) a. variables in python                                                       
variables are the location or a name, that can able to store a data interms of int, float, string etc                                                          
ex: name="Srinivas"

1) b. difference btw variable and constant                                      
variables are the location or a name, that can able to store a data interms of int, float, string etc                                                          
constant are the fixed value we can not alter that. there is no constant in python

2 a) & b)
   Datatypes
"""

x=50
type(x)

y=99.9
type(y)

name="srinivas"
type(name)

a=10
b=a>4
type(b)

""" 3a)Arithmatic operations"""

#1.addition
a=10
b=5
result=a+b
print(result)

# 2.substraction
a=10

b=5
result=a-b
print(result)

# 3.multiplication
a=10
b=5
result=a*b
print(result)

# 4.division
a=10
b=5
result=a/b
print(result)

# 5.modulud
a=10
b=3
result=a%b
print(result)

# 6.exponentation
a=2
b=3
result=a**b
print(result)

# 7.floor division
a=10
b=3
result=a//b
print(result)

""" 3 b)area of rectangle"""

l=5
w=10
area=l*w
print(area)

""" 4 a)Comparision and logical operation"""

#  1.equal
a=5
b=5
a==5

#  2.not equal
a=5
b=5
a!=5

#  3.greater than
a=5
b=3
a>b

#  4.lesser than
a=5
b=3
a<b

#  3.greater than or equal
a=5
b=3
a>=b

#  3.less than or equal
a=10
b=30
a<=b

"""4) b. using logical operator write a python script that check if a num is positive and even"""

num=int(input("enter a number"))
if num>0 and num%2==0:
    print("the number is positive and even")
else :
    print("the number is not positive and even")

"""5) a. type casting                                                              
converting one type of data into anther type                                    
implicit: automatically it convert one type into another type of data           
ex: a=10   b=5.5
     r=a+b                                                                      
explicit: manually we convert the data type of a variable                       
ex: a="1000"          
r=int(a)

5 b)python script for
"""

# 1.convert float to an int
x=55.55
y=int(x)
print(y)
type(y)

# 1.convert int to an str
x=1000
b=str(a)
print(b)
type(b)

# 1.convert str to an float
a="123.5"
b=float(a)
print(b)
type(b)

"""6) write a python script for.."""

# 1.adding two num
x=20
y=5
result=x+y
print(result)

# 2.sub
x=20
y=5
result=x-y
print(result)

# 3.multiply two num
x=20
y=5
result=x*y
print(result)

# 4.division
x=20
y=5
result=x/y
print(result)

# 5.convert the sum of the num to a str and print the type of result
a=1000
b=2000
result=a+b
str(result)
type(str(result))



